# I am a comment, and I want to say that the variable CC will be
# the compiler to use.
CC=g++
# Hey!, I am comment number 2. I want to say that CFLAGS will be the
# options I'll pass to the compiler.
CFLAGS= -Ofast -g -std=c++11

all: IBM2

IBM2: IBM2.cpp
	$(CC) $(CFLAGS) IBM2.cpp -o IBM2 

clean:
	rm IBM2